exclude:
    - node_modules
    - native-new
    - src
    - lib
    - examples

remote_theme: pmarsceill/just-the-docs
markdown: gfm

aux_links:
  "Discord":
    - "https://discord.gg/zQwyzFb"
  "Gitter":
    - "https://gitter.im/node-webrender/community"
  "GitHub":
    - "//github.com/cztomsik/stain"

# actually, it's this + /project_name
url: //tomsik.cz
